### ISSUE TITLE
Ilastik uint16 error

### ISSUE THREAD

**Issue by drpatelh** [nf-core/imcyto#12]
See https://github.com/ilastik/ilastik/issues/2162 for details

**Comment by drpatelh** [comment]
@KarishmaVal Can we close this now? or is the bug still there?

**Comment by KarishmaVal** [comment]
@drpatelh The bug is still there in the container 1.3.3post1, but a workaround is to use the 1.3.3b1 container instead.

**Comment by drpatelh** [comment]
Ok. Ill close this then 👍
