### ISSUE TITLE
request function - restart from custom point in pipeline

### ISSUE THREAD

**Issue by SBata** [nf-core/imcyto#40]
I was wondering if it's possible to restart the nf-core/imcyto pipeline from a specific point, this would be very useful in case we have to tweak something about cell segmentation, object identification etc...
for example from the image below 
<img width="997" alt="Screen Shot 2020-10-29 at 12 21 18 PM" src="https://user-images.githubusercontent.com/10268015/97602096-4885db00-19e1-11eb-8b41-472a4941010e.png">
everything worked well, but let's say I need to edit the segmentation step.
I'd like to go back, edit the `segmentation.cppipe` file as needed and then re-run that step....the `-resume` argument is awesome, I'm wondering whether it's possible to add something like `-resume_segmentation` or similar

**Comment by drpatelh** [comment]
The `-resume` function should be rerun if you change the segmentation step @SBata. Is it not doing that? The pipeline should only resume from steps where you have made a change to the input files or parameters.

**Comment by SBata** [comment]
ah that's good to know then! I thought that the `-resume` function only worked when there was an error in the pipeline. glad to know it, that's going to be really useful! thank you :)

**Comment by drpatelh** [comment]
Cool!
